export const interviewQuestions = {
  universityAndStudyPlans: {
    1: "Which university are you planning to attend?",
    2: "What is the program that you are applying?",
    3: "Why do you want the visa today?",
    4: "Why this Hybrid program why not to go with normal program",
    5: "Did you apply to any other universities?",
    6: "How many other universities have you applied to?",
    7: "List the names of the universities, you got accepted to. which one?",
    8: "Why did you only apply to just one university?",
    9: "What’s unique about this university?",
    10: "Why did you choose this university?",
    11: "Why did you choose this program?",
    12: "What are the components of this program?",
    13: "Why not study in your home country?",
    14: "Why do you want to study in the USA?",
    15: "What attracts you to the USA?",
  },
  academicsHistory: {
    1: "Where did you get your bachelor's degree?",
    2: "When did you graduate?",
    3: "What was your GPA?",
    4: "What did you study?",
    5: "What was your GRE/GMAT score?",
    6: "What was your TOEFL score?",
  },
  studentFinances: {
    1: "Who will be paying for your education?",
    2: "Who is sponsoring you?",
    3: "What funds will they use to pay for your studies?",
    4: "What is their income?",
    5: "How long have they worked in their job?",
    6: "How much money do they have in bank account?",
    7: "Any other asset your sponsor owns?",
    8: "How much does your program cost?",
    9: "How are you planning to pay other expenses? like housing food, and living expenses?",
  },
  workExperience: {
    1: "What is your current job title?",
    2: "What is your current salary?",
    3: "What your daily responsibilities look like?",
    4: "How long have you worked in the industry?",
    5: "How do You have 5 years when you just graduated in 2021?",
    6: "How long have you been at your current job?",
    7: "Have you received any promotions?",
    8: "Why did you take a gap year?",
    9: "Why are you leaving the workforce?",
  },
  postGraduationPlans: {
    1: "Do you plan to work in the USA after graduating?",
    2: "Do you plan to stay in USA after study?",
    3: "Do you plan to return to your home country after graduating?",
    4: "Why not the USA, The USA has lots of IT companies?",
    5: "How do you plan to repay the loan?",
  },
  otherQuestions: {
    1: "How many siblings do you have?",
    2: "What did your father do?",
    3: "Do you live with your family?",
    4: "Who lives in your house?",
    5: "Who all are part of your family?",
    6: "Did you apply to any other countries?",
    7: "Why did you change your field of study?",
    8: "Do you have any scholarship?",
    9: "My university has a high acceptance rate but a low graduation rate.",
  },
};
